### PR TITLE
Support `background`

### PR DESCRIPTION
**Pull request by przepompownia**

### CODE REVIEW

**Comment by przepompownia** [comment]
@tummetott thanks for rewriting. The original plugin didn't even switch to using `<Cmd>` (maybe for BC reasons) so commands at the RHS of mappings are visible on the input field there.

**Comment by tummetott** [comment]
Thank for the PR ❤️ 

I've actually already written the functions for background. See:
https://github.com/tummetott/unimpaired.nvim/blob/3ed9403493dcba780cadf8e87a019d7b70ca6a74/lua/unimpaired/functions.lua#L220-L231

I just forgot to add them in `config.lua` and `README.md`. 

Can you exclude your changes in `functions.lua`, then I'm happy to merge.

**Comment by tummetott** [comment]
> The original plugin didn't even switch to using <Cmd> (maybe for BC reasons) so commands at the RHS of mappings are visible on the input field there.

@przepompownia  I'm not sure if I understand you here. Can you explain that in more detail?

**Comment by przepompownia** [comment]
My English can be still poor. My comment does not matter for this PR. It had to explain why I started to find any alternative to the original plugin. For details please look into

https://github.com/tpope/vim-unimpaired/blob/6d44a6dc2ec34607c41ec78acf81657248580bf1/plugin/unimpaired.vim#L43-L70

**Comment by przepompownia** [comment]
Indeed! Not finding needed config key I did not assume that the implementation can already exist...

**Comment by przepompownia** [comment]
> @przepompownia I'm not sure if I understand you here. Can you explain that in more detail?

In practice, `yob` caused opening Noice input while to "typing" the related command :grin:

**Comment by tummetott** [comment]
> In practice, yob caused opening Noice input while to "typing" the related command 😁

you mean in `topopes` plugin?

Thank you for the PR

**Comment by przepompownia** [comment]
> you mean in `topopes` plugin?

Yes, as under the link above. 

Thank you too.

**Pull request merged**
